dist: trusty

# Travis CI build matrix.  Each entry below will trigger an extra, parallel build on Travis.
matrix:
  include:

  - language: java
    os: linux
    jdk: openjdk11
    # Override ./gradlew and use gradle instead to overcome errors
    install: gradle assemble
    script: gradle check


