dist: trusty

# Travis CI build matrix.  Each entry below will trigger an extra, parallel build on Travis.
matrix:
  include:

  # Compile Java as usual
  - language: java
    os: linux
    jdk: oraclejdk8

  # Compile Java as usual
  - language: java
    os: linux
    jdk: oraclejdk11

